# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38abbca4edf493ddfa273920f5cb16e00d6853a1233fef78ce6b26c62ed0515f25341e397179b10acb6f757ae60188d68a67068f09d2d123a33fa1b96e835266

test:
  secret_key_base: c58cc3f85b5248546059b22d23e04be9e882ce27c39b5056e6f71c9e07749cd7bb7e99a404e7b6080bf7b3c37079dfc7cf08b727ab1483e50d620f737849e282

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
