Feature: read_after order

  Scenario: Changing read after orders
    Given 5 pages exist
    When I am on the homepage
    Then I should see "Page 1" within "#position_1"
      And I should see "Page 2" within "#position_2"
      And I should see "Page 3" within "#position_3"
      And I should see "Page 4" within "#position_4"
      And I should see "Page 5" within "#position_5"
    When I follow "Page 1" within "#position_1"
      And I follow "Rate"
    Then I should see "Please rate (converted to years for next suggested read date)"
    When I choose "boring"
      And I choose "stressful"
    And I press "Rate"
    Then I should see "Page 1 set for reading again in 4 years"
      And I should see "Page 2" within "#position_1"
      And I should see "Page 3" within "#position_2"
      And I should see "Page 4" within "#position_3"
      And I should see "Page 5" within "#position_4"
      And I should see "Page 1" within "#position_5"
    When I follow "Page 2" within "#position_1"
      And I follow "Rate"
      And I choose "interesting enough"
      And I choose "stressful"
    And I press "Rate"
    Then I should see "Page 2 set for reading again in 3 years"
      And I should see "Page 3" within "#position_1"
      And I should see "Page 4" within "#position_2"
      And I should see "Page 5" within "#position_3"
      And I should see "Page 2" within "#position_4"
      And I should see "Page 1" within "#position_5"
    When I follow "Page 3" within "#position_1"
      And I follow "Rate"
      And I choose "sweet enough"
      And I choose "boring"
    And I press "Rate"
    Then I should see "Page 3 set for reading again in 3 years"
      And I should see "Page 4" within "#position_1"
      And I should see "Page 5" within "#position_2"
      And I should see "Page 2" within "#position_3"
      And I should see "Page 3" within "#position_4"
      And I should see "Page 1" within "#position_5"
    When I follow "Page 4" within "#position_1"
      And I follow "Rate"
      And I choose "very interesting"
      And I choose "sweet enough"
    And I press "Rate"
    Then I should see "Page 4 set for reading again in 1 years"
      And I should see "Page 5" within "#position_1"
      And I should see "Page 4" within "#position_2"
      And I should see "Page 2" within "#position_3"
      And I should see "Page 3" within "#position_4"
      And I should see "Page 1" within "#position_5"
    When I follow "Page 5" within "#position_1"
      And I follow "Rate"
      And I choose "boring"
      And I choose "stressful"
    And I press "Rate"
    Then I should see "Page 5 set for reading again in 4 years"
      And I should see "Page 4" within "#position_1"
      And I should see "Page 2" within "#position_2"
      And I should see "Page 3" within "#position_3"
      And I should see "Page 1" within "#position_4"
      And I should see "Page 5" within "#position_5"
