Feature: read_after order

  Scenario: Changing read after order by rating a page
    Given I have no pages
    And 5 pages exist
    When I am on the homepage
    Then I should see "Page 1" within "#position_1"
      And I should see "Page 2" within "#position_2"
      And I should see "Page 3" within "#position_3"
      And I should see "Page 4" within "#position_4"
      And I should see "Page 5" within "#position_5"
    When I follow "Page 1" within "#position_1"
      And I follow "Rate"
    Then I should see "Rate Page 1"
    When I choose "2"
    And I press "Rate"
    Then I should see "Page 1 set for reading again"
    When I am on the homepage
      And I should see "Page 2" within "#position_1"
      And I should see "Page 3" within "#position_2"
      And I should see "Page 4" within "#position_3"
      And I should see "Page 5" within "#position_4"
      And I should see "Page 1" within "#position_5"
    When I follow "Page 2" within "#position_1"
      And I follow "Rate"
      And I choose "4"
    And I press "Rate"
    Then I should see "Page 2 set for reading again"
    When I am on the homepage
      Then I should see "Page 3" within "#position_1"
      And I should see "Page 4" within "#position_2"
      And I should see "Page 5" within "#position_3"
      And I should see "Page 2" within "#position_4"
      And I should see "Page 1" within "#position_5"
    When I follow "Page 3" within "#position_1"
      And I follow "Rate"
      And I choose "3"
    And I press "Rate"
    Then I should see "Page 3 set for reading again"
    When I am on the homepage
      Then I should see "Page 4" within "#position_1"
      And I should see "Page 5" within "#position_2"
      And I should see "Page 2" within "#position_3"
      And I should see "Page 3" within "#position_4"
      And I should see "Page 1" within "#position_5"
    When I follow "Page 4" within "#position_1"
      And I follow "Rate"
      And I choose "5"
    And I press "Rate"
    Then I should see "Page 4 set for reading again"
    When I am on the homepage
      Then I should see "Page 5" within "#position_1"
      And I should see "Page 4" within "#position_2"
      And I should see "Page 2" within "#position_3"
      And I should see "Page 3" within "#position_4"
      And I should see "Page 1" within "#position_5"
    When I follow "Page 5" within "#position_1"
      And I follow "Rate"
      And I choose "1"
    And I press "Rate"
    Then I should see "Page 5 set for reading again"
    When I am on the homepage
      Then I should see "Page 4" within "#position_1"
      And I should see "Page 2" within "#position_2"
      And I should see "Page 3" within "#position_3"
      And I should see "Page 1" within "#position_4"
      And I should see "Page 5" within "#position_5"
