Feature: complex parts with titles from url list

  Scenario: create parts from a list of urls with titles
    Given I am on the homepage
      And I follow "Store Multiple"
    When I fill in "page_urls" with "#First\nhttp://www.rawbw.com/~alice/parts/1.html\n#Second\nhttp://www.rawbw.com/~alice/parts/2.html"
     And I fill in "page_title" with "Pages from urls with titles"
     And I press "Store"
   Then I should see "Pages from urls with titles"
     And I should see "stuff for part 1"
     And I should see "stuff for part 2"
   When I follow "Read"
     And I should see "First"
     And I should see "Second"
   When I follow "Manage Parts"
   Then I should see "#First" in ".parts"
     And I should see "#Second" in ".parts"
   When I fill in "url_list" with "#First Parent\n##First Sub 1\nhttp://www.rawbw.com/~alice/parts/1.html\n##First Sub 2\nhttp://www.rawbw.com/~alice/parts/2.html\n#Second Parent\n##Second Sub 1\nhttp://www.rawbw.com/~alice/parts/3.html\n##Second Sub 2\nhttp://www.rawbw.com/~alice/parts/4.html\n#Third Parent\nhttp://www.rawbw.com/~alice/test.html"
       And I press "Update"
   When I follow "Read"
   Then I should see "First Parent" in "h1"
     And I should see "First Sub 1" in "h2"
     And I should see "stuff for part 1"
     And I should see "First Sub 2" in "h2"
     And I should see "stuff for part 2"
     And I should see "Second Parent" in "h1"
     And I should see "Second Sub 1" in "h2"
     And I should see "stuff for part 3"
     And I should see "Second Sub 2" in "h2"
     And I should see "stuff for part 4"
     And I should see "Third Parent" in "h1"
     And I should see "Retrieved from the web"
