Feature: filter by type

  Scenario: filter on types
    Given I have no pages
      And a page exists with title: "Single" AND url: "http://test.sidrasue.com/short.html"
      And a page exists with title: "Novel" AND base_url: "http://test.sidrasue.com/long*.html" AND url_substitutions: "1 2"
      And a page exists with title: "Trilogy" AND urls: "##Alpha,http://test.sidrasue.com/parts/1.html###Prologue,##Beta,http://test.sidrasue.com/parts/5.html###Epilogue"
    When I am on the homepage
      Then I should see "Single"
      And I should see "Novel"
      And I should see "Trilogy"
      But I should NOT see "Part 1 of Novel"
      And I should NOT see "Alpha of Trilogy"
      And I should NOT see "Prologue"
      And I should NOT see "Epilogue"
    When I choose "type_none"
      And I press "Find"
      Then I should see "No pages found"
    When I choose "type_Chapter"
      And I press "Find"
      Then I should see "Single"
      And I should see "Part 1 of Novel"
      And I should see "Part 2 of Novel"
      And I should see "Prologue of Alpha of Trilogy"
      And I should see "Epilogue of Beta of Trilogy"
    When I choose "type_Book"
      And I press "Find"
      Then I should see "Novel"
      And I should see "Alpha of Trilogy"
      And I should see "Beta of Trilogy"
      But I should NOT see "Single"
      And I should NOT see "Part 1 of Novel"
      And I should NOT see "Prologue of Alpha"
    When I choose "type_Series"
      And I press "Find"
      Then I should see "Trilogy"
      But I should NOT see "Single"
      And I should NOT see "Novel"
      And I should NOT see "Alpha of Trilogy"
