Feature: page size

  Scenario: filter on a size
    Given the following pages
      | title  | url                                   |
      | Drabble  | http://test.sidrasue.com/test.html   |
      | Short  | http://test.sidrasue.com/short.html   |
      | Medium | http://test.sidrasue.com/long.html  |
      | Long   | http://test.sidrasue.com/40000.html    |
    And a page exists with title: "Medium2" AND base_url: "http://test.sidrasue.com/medium*.html" AND url_substitutions: "1-5"
    And a page exists with title: "Long2" AND base_url: "http://test.sidrasue.com/long*.html" AND url_substitutions: "1-9"
    And a page exists with title: "Epic" AND base_url: "http://test.sidrasue.com/epic/epic*.html" AND url_substitutions: "1-9"
    When I am on the homepage
    Then I should see "Drabble" within "#position_1"
      And I should see "Short" within "#position_2"
      And I should see "Medium" within "#position_3"
      And I should see "Long" within "#position_4"
      And I should see "Medium2" within "#position_5"
      And I should see "Long2" within "#position_6"
      And I should see "Epic" within "#position_7"
    When I choose "size_drabble"
      And I press "Find"
    Then I should see "Drabble" within "#position_1"
      And I should NOT see "Short"
      And I should NOT see "Medium"
      And I should NOT see "Long"
      And I should NOT see "Epic"
      And I should NOT see "Part"
    When I choose "size_short"
      And I press "Find"
    Then I should see "Short" within "#position_1"
      But I should NOT see "Drabble"
      And I should NOT see "Medium"
      And I should NOT see "Long"
      And I should NOT see "Epic"
      And I should NOT see "Part"
    When I choose "size_medium"
      And I press "Find"
    Then I should see "Medium" within "#position_1"
      And I should see "Medium2" within "#position_2"
      And I should NOT see "Drabble"
      And I should NOT see "Short"
      And I should NOT see "Long"
      And I should NOT see "Epic"
    When I choose "size_long"
      And I press "Find"
    Then I should see "Long" within "#position_1"
      And I should see "Long2" within "#position_2"
      And I should NOT see "Drabble"
      And I should NOT see "Short"
      And I should NOT see "Medium"
      And I should NOT see "Epic"
      And I should NOT see "Part"
    When I choose "size_longer"
      And I press "Find"
    Then I should see "Long" within "#position_1"
      And I should see "Long2" within "#position_2"
      And I should see "Epic" within "#position_3"
      And I should NOT see "Drabble"
      And I should NOT see "Short"
      And I should NOT see "Medium"
      And I should NOT see "Part"
    When I choose "size_shorter"
      And I press "Find"
      Then I should see "Drabble" within "#position_1"
      And I should see "Short" within "#position_2"
      But I should NOT see "Medium"
      And I should NOT see "Long"
      And I should NOT see "Epic"
